app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
from app import create_app,db


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
                
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index =True)
    firstname = db.Column(db.String(255))
    lastname = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(5000))
    profile_pic_path = db.Column(db.String)
    pass_secure = db.Column(db.String(255))
    date_joined = db.Column(db.DateTime,default=datetime.utcnow)

    pitches = db.relationship('Pitch',backref = 'user',lazy = "dynamic")

    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_title = db.Column(db.String)
    pitch_content = db.Column(db.String(1000))
    category = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)

    comments = db.relationship('Comment',backref =  'pitch_id',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,category):
        pitches = Pitch.query.filter_by(category=category).all()
        return pitches

    @classmethod
    def get_pitch(cls,id):
        pitch = Pitch.query.filter_by(id=id).first()

        return pitch

    

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(1000))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch):
        comments = Comment.query.filter_by(pitch_id=pitch).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Write a brief bio about you.',validators = [Required()])
    submit = SubmitField('Save')

class PitchForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    category = SelectField('Category', choices=[('Events','Events'),('Job','Job'),('Advertisement','Advertisement')],validators=[Required()])
    post = TextAreaField('Your Pitch', validators=[Required()])
    submit = SubmitField('Pitch')

class CommentForm(FlaskForm):
    comment = TextAreaField('Leave a comment',validators=[Required()])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail


    


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db=SQLAlchemy()
mail = Mail()



def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    



    # Initializing flask extensions

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    # Will add the views and forms

    # configure UploadSet
    

    
    


#Registering the blueprint


    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)


    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from .views import *
from . import views,forms

app/main/views.py
from flask import render_template, redirect, url_for,abort,request
from . import main
from flask_login import login_required,current_user
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,PitchForm,CommentForm


@main.route('/')
def index():
    pitches = Pitch.query.all()
    job = Pitch.query.filter_by(category = 'Job').all() 
    event = Pitch.query.filter_by(category = 'Events').all()
    advertisement = Pitch.query.filter_by(category = 'Advertisement').all()
    return render_template('index.html', job = job,event = event, pitches = pitches,advertisement= advertisement)

@main.route('/create_new', methods = ['POST','GET'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        
        post = form.post.data
        category = form.category.data
        user_id = current_user
        new_pitch_object = Pitch(pitch_content=post,user_id=current_user._get_current_object().id,category=category)
        new_pitch_object.save_pitch()
        return redirect(url_for('main.index'))
        
    return render_template('create_pitch.html', form = form)

@main.route('/comment/<int:pitch_id>', methods = ['POST','GET'])
@login_required
def comment(pitch_id):
    form = CommentForm()
    pitch = Pitch.query.get(pitch_id)
    all_comments = Comment.query.filter_by(pitch_id = pitch_id).all()
    if form.validate_on_submit():
        comment = form.comment.data 
        pitch_id = pitch_id
        user_id = current_user._get_current_object().id
        new_comment = Comment(comment = comment,user_id = user_id,pitch_id = pitch_id)
        new_comment.save_c()
        return redirect(url_for('.comment', pitch_id = pitch_id))
    return render_template('comment.html', form =form, pitch = pitch,all_comments=source)


@main.route('/user/<name>')
def profile(name):
    user = User.query.filter_by(username = name).first()
    user_id = current_user._get_current_object().id
    posts = Pitch.query.filter_by(user_id = user_id).all()
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user,posts=posts)

@main.route('/user/<name>/updateprofile', methods = ['POST','GET'])
@login_required
def updateprofile(name):
    form = UpdateProfile()
    user = User.query.filter_by(username = name).first()
    if user == None:
        abort(404)
    if form.validate_on_submit():
        user.bio = form.bio.data
        user.save_u()
        return redirect(url_for('.profile',name = name))
    return render_template('profile/update.html',form =form)


@main.route('/user/<name>/update/pic',methods= ['POST'])
@login_required
def update_pic(name):
    user = User.query.filter_by(username = name).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',name=name))

@main.route('/like/<int:id>',methods = ['POST','GET'])
@login_required
def like(id):
    get_pitches = Upvote.get_upvotes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.index',id=id))
        else:
            continue
    new_vote = Upvote(user = current_user, pitch_id=id)
    new_vote.save()
    return redirect(url_for('main.index',id=id))

@main.route('/dislike/<int:id>',methods = ['POST','GET'])
@login_required
def dislike(id):
    pitch = Downvote.get_downvotes(id)
    valid_string = f'{current_user.id}:{id}'
    for p in pitch:
        to_str = f'{p}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.index',id=id))
        else:
            continue
    new_downvote = Downvote(user = current_user, pitch_id=id)
    new_downvote.save()
    return redirect(url_for('main.index',id = id))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-144351462-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-144351462-1');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Piches</title>
    {% block styles %}
    <link href="https://fonts.googleapis.com/css?family=Arimo|Farro|Livvic&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">
    
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
    {% endblock %}
</head>


<body class="body" style="background-color: rgb(124, 45, 45);" ></body>
        {% block navbar %}
        {% include "navbar.html" %}
        {% endblock %}
        {% block content %}
        {% endblock %}
{% block scripts %}

<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.4.1.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/particles.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
<script src="particles.js" type="text/javascript"></script>
<script src="app.js" type="text/javascript"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/js/mdb.min.js"></script>
{% endblock %}
</body>
</html>

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container" id="allcomments" >
        <div class="row">

            {% if all_comments %}
                <div class="col-md-7" >
                    <h3 class="text-center" id="coms">All comments for the post</h3>
                    {% for comment in all_comments %}
                       <div class="card w-90 mb-3" >
                           <div class="card-body">
                            <h5>{{comment.pitch.title}}</h5>
                             <p class="card-title">{{ comment.comment }}</p>
                             <p class="card-text">--- {{comment.user.username}}</p>
                           </div>
                       </div>
                    {% endfor %}
                   </div>
                   <div class="col-md-5  commentform" >

                        {{wtf.quick_form(form)}}
                   </div>
               </div>
            {%else%}
            <div class="card w-90 mb-3">
                <div class="card-body">
                  <p class="card-title">No Comments for this yet for this post. Be the first to comment</p>
                </div>
            </div> 
            <div class="col-md-5">
                    {{wtf.quick_form(form)}}
                </div>
            {%endif%}
    </div>
   
{% endblock%}

app/templates/create_pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}

    <div  id="particles-js"  >  
            <div class=" row" >
                    
                    <div class="col-md-2"></div>
                    <div class="col-md-8" id="postform">
                        <h2 class="text-center">Create Your Pitch Here!</h2>
                        {{wtf.quick_form(form)}}
                    </div>
                    <div class="col-md-2"></div>
            </div>
    </div>
   
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}
    
        <div  class="container" id="particles-js">
                <h2 class="text-center" id="posts">All Pitches</h2>
            <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
                <li class="nav-item" >
                    <a id ="cats" class="nav-link" data-toggle="tab" href="#all"><strong>All Pitches</strong> </a>
                </li>
               
            </ul>
            <li class="text-center text-light">
                <a href="/create_new">Add Your Pitch</a>
            </li>
            <div class="tab-content text-center">
                <div  class="container tab-pane active" id="all"><br>
                    {{ macro.display(pitches) }}
                </div>
                
            </div>
        </div>
{% endblock%}

app/templates/macros.html
{% macro display(piches) %}
 <div class="container-fluid">
         <div class="row">
                 {% if piches %}
                     {% for category in piches %}
                     <div class="col-md-12" >
                         <div class="thumbnail" id="carded">
                             <h5 class="card-header">{{category.title}}</h5>
                             <div class="card-body">
                                     <p>{{category.post}}</p>
                                     <p class="text-center"> Category: {{category.category}}</p>
                                     <footer class="blockquote-footer text-center" > Posted by: {{category.user.username}}</footer>
                                 <div><span class="foot" >{{category.comments .count()}} Comments</span> 
                                     <span class="foot" > <a href="{{url_for('main.like',id = category.id)}}"><i class="fa fa-thumbs-up" style="font-size:18px;color: green"></i></a></span>
                                     
                                     
                                     <span class="foot"> <a href="{{url_for('main.dislike',id = category.id)}}"> <i class="fa fa-thumbs-down" style="color:red;"></i></a></span></div>
             
                                 <a href="{{url_for('main.comment',pitch_id = category.id)}}" class="btn btn-secondary btn-sm"> Comment</a>
                             </div>
                         </div>
                     </div>
                     
                     {% endfor %}
                 {% else %}
                 <div class="card w-90 mb-3">
                     <div class="card-body">
                 
                         <p class="card-title">Category Has 0 posts</p>
                     </div>
                 </div>
                 {% endif %}
             </div>
 </div>
 {% endmacro %}

app/templates/marcos.html
{% macro display(piches) %}
 <div class="container-fluid">
         <div class="row">
                 {% if piches %}
                     {% for category in piches %}
                     <div class="col-md-4" >
                         <div class="thumbnail" id="carded">
                             <h5 class="card-header">{{category.title}}</h5>
                             <div class="card-body">
                                     <p>{{category.post}}</p>
                                     <p class="text-center"> Category: {{category.category}}</p>
                                     <footer class="blockquote-footer text-center" > Posted by: {{category.user.username}}</footer>
                                 <div><span class="foot" >{{category.comment.count()}} Comments</span> 
                                     <span class="foot" > <a href="{{url_for('main.like',id = category.id)}}"><i class="fa fa-thumbs-up" style="font-size:18px;color: green"></i></a> {{category.upvote.count()}}</span>
                                     
                                     
                                     <span class="foot"> <a href="{{url_for('main.dislike',id = category.id)}}"> <i class="fa fa-thumbs-down" style="color:red;"></i> {{category.downvote.count()}}</a></span></div>
             
                                 <a href="{{url_for('main.comment',pitch_id = category.id)}}" class="btn btn-info btn-sm"> Comment</a>
                             </div>
                         </div>
                     </div>
                     
                     {% endfor %}
                 {% else %}
                 <div class="card w-90 mb-3">
                     <div class="card-body">
                 
                         <p class="card-title">Category Has 0 posts</p>
                     </div>
                 </div>
                 {% endif %}
             </div>
 </div>
 {% endmacro %}

app/templates/navbar.html
 
<nav class="mb-1 navbar navbar-expand-lg navbar-dark ">
    <a class="navbar-brand" href="{{url_for('main.index')}}"><strong>Clock-Me</strong> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('main.index')}}"></a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.new_pitch')}}">New Pitch</a>
                </li>
                {% endif %}
            </ul>
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style= 'margin-right:30px' data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user"></i>&nbsp;<strong>{{current_user.username}}</strong> </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
              <a class="dropdown-item" href="{{url_for('main.profile',name=current_user.username)}}"><i class="far fa-user"></i>&nbsp; My account</a>
              <a class="dropdown-item" href="{{url_for('auth.logout')}}"><i class="fas fa-sign-out-alt"></i>&nbsp; Log out</a>
            </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a  class="nav-link" href="{{url_for('auth.login')}}" style= 'margin-right:30px'><i class="fas fa-sign-in-alt"></i>&nbsp; <strong>Log In</strong></a>
            </li>
            <li class="nav-item">
                    <a style= 'margin-right:30px' class="nav-link" href="{{url_for('auth.signup')}}"><i class="fas fa-user-plus"></i></i>&nbsp; <strong>Sign Up</strong></a>
                </li>
            {%endif%}

        </ul>
    </div>
</nav>

app/templates/profile/profile.html
 
{% extends 'base.html'%}

{% block content %}
<div class="container" style="margin-top: 1%">
<div class="row">
  <div class="col-md-4 pict" >
      

    <div class="card testimonial-card">
        <div class="card-img"  >
                {% if user.profile_pic_path %}
                <img src="{{url_for('static',filename=user.profile_pic_path)}}" style="height:300px;border-radius: 1%" class="card-img"  alt="woman avatar">            
                {%else%}
                <p>No profile picture</p>
            
                {% endif %}  
        </div>

        <div class="card-body">
            <h5 class="text-center"> {{user.username| capitalize}}</h5>
            <hr>
            {% if user.bio %}
                <p><i class="fas fa-quote-left"></i> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
            {% if user == current_user %}
            <div class="profpic">
                <div id="updates">
                  <a href="{{url_for('main.updateprofile',name=user.username)}}">Edit Bio</a>
                  <button class="btn btn-sm btn-info" id="profbutton">update pic</button>
                </div>
                
                <div id="imgform">
                    <form  action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype = "multipart/form-data">
                      <input type="file"  name="photo" class="form-control" required>
                      <input type="submit" class="btn btn-sm btn-info" id="submit">
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
  </div>
  <div class="col-md-1"></div>
    <div class="col-md-5" id="user">
        {% if current_user %}
        <h3 class="text-center">You have {{user.pitches.count()}} Pitches</h3>
        {% for i in posts%}
        <div class="pitches">
            <h5>Title: {{i.title}}</h5>
            <h6>{{i.post}}</h6>
            <p>{{i.comment.count()}} Comments</p>
        </div>
         
        {%endfor%}
        {%else%}
        <h3>You have ) posts</h3>
        {%endif%}

  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6 updateprofile" >
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-sm-3"></div>
    </div> 
</div>
{% endblock %}